spring:
  datasource:
    url: jdbc:mysql://localhost/db_springboot_backend_mercadona?useSSL=false
    username: root
    password: sasa
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create-drop